// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLAE-pREXw0lAvX3JAEj_7lvbVPJw6hVg',
    appId: '1:474201715625:android:a08239f0b9e335fbb14ab8',
    messagingSenderId: '474201715625',
    projectId: 'emoney-project-a25e6',
    storageBucket: 'emoney-project-a25e6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46uBUvmVQKsSL7HIXZG58MD9jXQCFX7c',
    appId: '1:948878883710:ios:5363ad2b9fbe06b2a0512f',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
    iosBundleId: 'com.kampus.dompetKampusGlobal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksFCfCdyFuV5i0XSdT1pQm6wSe1VLBSg',
    appId: '1:474201715625:web:ca703b02897e82b3b14ab8',
    messagingSenderId: '474201715625',
    projectId: 'emoney-project-a25e6',
    authDomain: 'emoney-project-a25e6.firebaseapp.com',
    storageBucket: 'emoney-project-a25e6.firebasestorage.app',
    measurementId: 'G-QRXFP9223X',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCksFCfCdyFuV5i0XSdT1pQm6wSe1VLBSg',
    appId: '1:474201715625:web:63974cae624b966db14ab8',
    messagingSenderId: '474201715625',
    projectId: 'emoney-project-a25e6',
    authDomain: 'emoney-project-a25e6.firebaseapp.com',
    storageBucket: 'emoney-project-a25e6.firebasestorage.app',
    measurementId: 'G-FQBK5VHN34',
  );
}
