// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0eQUfus6ed1gbJkNNDpK0GWKwWUyrO_8',
    appId: '1:701230577881:web:69580aaf961c76db24a6c8',
    messagingSenderId: '701230577881',
    projectId: 'emoney-project-83650',
    authDomain: 'emoney-project-83650.firebaseapp.com',
    storageBucket: 'emoney-project-83650.firebasestorage.app',
    measurementId: 'G-XR4MMW44Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZp56rjv_dXc1tvbVDGLWY7BauGpEX9fk',
    appId: '1:701230577881:android:c791e1311ceb7bc724a6c8',
    messagingSenderId: '701230577881',
    projectId: 'emoney-project-83650',
    storageBucket: 'emoney-project-83650.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0eQUfus6ed1gbJkNNDpK0GWKwWUyrO_8',
    appId: '1:701230577881:web:69580aaf961c76db24a6c8',
    messagingSenderId: '701230577881',
    projectId: 'emoney-project-83650',
    authDomain: 'emoney-project-83650.firebaseapp.com',
    storageBucket: 'emoney-project-83650.firebasestorage.app',
    measurementId: 'G-XR4MMW44Y1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATGxhFRusjQkumoMh-JBLcpi5B_5fcofc',
    appId: '1:701230577881:ios:e17691ad61272fa824a6c8',
    messagingSenderId: '701230577881',
    projectId: 'emoney-project-83650',
    storageBucket: 'emoney-project-83650.firebasestorage.app',
    iosClientId: '701230577881-8rjghnq6calrspr945hpvuhjv4aes77o.apps.googleusercontent.com',
    iosBundleId: 'com.example.dompetKampusGlobal',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATGxhFRusjQkumoMh-JBLcpi5B_5fcofc',
    appId: '1:701230577881:ios:e17691ad61272fa824a6c8',
    messagingSenderId: '701230577881',
    projectId: 'emoney-project-83650',
    storageBucket: 'emoney-project-83650.firebasestorage.app',
    iosClientId: '701230577881-8rjghnq6calrspr945hpvuhjv4aes77o.apps.googleusercontent.com',
    iosBundleId: 'com.example.dompetKampusGlobal',
  );
}
